package bike.store;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public class MenuItem extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    private boolean selected;
    private boolean hover;
    public MenuItem(menuModel data) {
        initComponents();
        this.setOpaque(false);
          if(data.getType() == menuModel.menuType.MENU)
          {
              laicon.setIcon(data.toIcon());
              laName.setText(data.getName());
          } else if (data.getType() == menuModel.menuType.TITLE)
          {
              laicon.setText(data.getName());
              laicon.setFont(new Font("sansserif",1,12));
              laName.setVisible(false);
          } else {
              laName.setText(" ");
          }
    }
    public void setSelected(boolean selected){
        this.selected =selected;
        repaint();
    }
    public void setHover(boolean hover){
        this.hover = hover;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laicon = new javax.swing.JLabel();
        laName = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(175, 35));

        laicon.setForeground(new java.awt.Color(255, 255, 255));

        laName.setForeground(new java.awt.Color(255, 255, 255));
        laName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        laName.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laicon)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(laicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents
   @Override
   protected void paintComponent(Graphics g)
   {
       if(selected || hover){
        Graphics2D g2 =(Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
       if(selected) {
           g2.setColor(new Color(249,242,220,80));
        } else {
           g2.setColor(new Color(249,242,220,20));
        }
        g2.fillRoundRect(10, 0, getWidth()-20, getHeight(),5,5);
       }
      super.paintComponent(g);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel laName;
    private javax.swing.JLabel laicon;
    // End of variables declaration//GEN-END:variables
}
