package bike.store;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;


public class Menu extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    public void addEventMenuSelected (EventMenuSelected event)
    {
        listMenu1.addEventMenuSelected(event);
    }
    public Menu() {
        initComponents();
        this.setOpaque(false);
        panelMoving.setBackground(new Color(0,0,0,0));
        listMenu1.setOpaque(false);
        init();
    }
    private void init(){
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"الأساسيات","bike-shop white"));
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"الحسابات","bike-shop color"));
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"السندات","bike-shop color-border"));
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"الفواتير","bike-shop color-border"));
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"التقارير","bike-shop color-border"));
        listMenu1.addItem(new menuModel(menuModel.menuType.EMPTY," "," "));
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"الإعدادات","bike-shop color-border"));
        listMenu1.addItem(new menuModel(menuModel.menuType.MENU,"تسجيل الخروج","bike-shop color-border"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listMenu1 = new bike.store.listMenu<>();

        setPreferredSize(new java.awt.Dimension(235, 600));

        panelMoving.setPreferredSize(new java.awt.Dimension(230, 81));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike/store/bike-shop color-border.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Application");

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMovingLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listMenu1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(listMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

     @Override
   protected void paintChildren(Graphics g)
   {
      Graphics2D g2 =(Graphics2D) g;
      g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
      GradientPaint gr = new GradientPaint(0,0,Color.decode("#f5af19"),0,getHeight(),Color.decode("#c46128"));
      g2.setPaint(gr);
      g2.fillRoundRect(0, 0, getWidth(), getHeight(),25,25);
      g2.fillRect(getWidth()-230, 0, getWidth()-200,getHeight());
      super.paintChildren(g);
   }
//   private int x;
//   private int y;
//   public void initMoving( JFrame frame)
//   {
//       panelMoving.addMouseListener(new MouseAdapter() {
//       @Override
//       public void mousePressed(MouseEvent m)
//       {
//           super.mousePressed(m);// to change body of generated methods
//           x = m.getX();
//           y = m.getY();
//       }});
//       panelMoving.addMouseMotionListener(new MouseMotionAdapter() {
//       @Override
//       public void mouseDragged(MouseEvent m)
//       {
//           frame.setLocation(m.getXOnScreen()-x, m.getYOnScreen()-y);
//       }
//       });
//       
//   }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private bike.store.listMenu<String> listMenu1;
    private javax.swing.JPanel panelMoving;
    // End of variables declaration//GEN-END:variables
}
